# Generated by Django 3.1.1 on 2020-09-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
