# Generated by Django 3.1.1 on 2020-09-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200925_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
