# Generated by Django 3.1.1 on 2020-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='action_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='turn',
            field=models.BooleanField(default=False),
        ),
    ]
